# Generated by Django 2.2.3 on 2019-07-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20190719_0840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventlog',
            options={'ordering': ['-date'], 'verbose_name': '事件纪录', 'verbose_name_plural': '事件纪录'},
        ),
        migrations.AddField(
            model_name='eventlog',
            name='address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址'),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='useragent',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='User_Agent'),
        ),
    ]
