# Generated by Django 2.2.3 on 2019-07-23 11:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20190719_0939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='software',
            options={'ordering': ['-id'], 'verbose_name': '软件/系统', 'verbose_name_plural': '软件/系统'},
        ),
        migrations.AddField(
            model_name='software',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='批准日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='software',
            name='m_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日期'),
        ),
    ]
