# Generated by Django 2.2.3 on 2019-07-18 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='用户名')),
                ('nickname', models.CharField(blank=True, max_length=64, null=True, verbose_name='昵称')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32, verbose_name='性别')),
                ('status', models.SmallIntegerField(choices=[(0, '启用'), (1, '禁用')], default=0, verbose_name='账号状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.SmallIntegerField(choices=[(0, '其他'), (1, '登陆'), (2, '退出'), (3, '登陆错误')], default=1, verbose_name='事件类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='事件时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.User', verbose_name='用户名')),
            ],
            options={
                'verbose_name': '登陆日志',
                'verbose_name_plural': '登陆日志',
                'ordering': ['-create_time'],
            },
        ),
    ]
