# Generated by Django 2.2.3 on 2019-07-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginlog',
            name='detail',
            field=models.TextField(default='登陆成功', verbose_name='事件详情'),
        ),
    ]
