# Generated by Django 2.2.3 on 2019-07-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_loginlog_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginlog',
            name='address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址'),
        ),
        migrations.AddField(
            model_name='loginlog',
            name='useragent',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='User_Agent'),
        ),
    ]
